spring:
  application:
    name: ocms
  
  # MySQL Configuration (Production)
  datasource:
    url: jdbc:mysql://localhost:3306/ocms_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # H2 Database Configuration (Development/Testing)
  # Uncomment the following lines to use H2 instead of MySQL
  # datasource:
  #   url: jdbc:h2:mem:ocms_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #   username: sa
  #   password: 
  #   driver-class-name: org.h2.Driver
  
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # For H2, use: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080

logging:
  level:
    com.ocms: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: ocmsSecretKeyForJWTTokenGenerationAndValidation2024
  expiration: 86400000 # 24 hours in milliseconds